'use strict';
const faces=[
{id:'mind',word:'思考',label:'思考的紋理',cat:'mind',en:'MIND',x:50,y:12,light:'先理解，再決定相信什麼。',edge:'挖得深，未必代表抓得準。',tease:'知道更多細節，和解決眼前問題，是兩回事。',cost:'你會從一個名詞追到原理，也曾自己提醒「怕窮盡到擱置重要的事」。這表示真正的瓶頸有時不是理解力，而是停在哪裡。若眼前只要確認規格，卻把整套原理都搬進來，時間花完了，決策未必前進。',next:'先寫下「我現在要做哪個決定」。只追會改變這個決定的問題；其餘進待查清單。',ground:'依據：你對深入技術原理的追問，以及自己提出的時間界線。'},
{id:'language',word:'語言',label:'語言的分寸',cat:'work',en:'LANGUAGE',x:76,y:23,light:'準確之外，還要有分寸。',edge:'想交代完整，反而淹沒重點。',tease:'每句都沒錯，不代表對方知道你到底要什麼。',cost:'你曾說，日文表達容易卡在核心訊息和多餘細節。當每個背景都捨不得刪，一封信可能很周全，卻要讀者自己找結論。把句子修得更禮貌，救不了訊息順序。',next:'先用一句話交代「要對方確認什麼、何時回覆」。第二段才放足以做決定的背景；刪去不影響回覆的資訊。',ground:'依據：你自己描述的日文表達難點；不是對所有郵件的判定。'},
{id:'work',word:'工作',label:'工作的座標',cat:'work',en:'WORK',x:87,y:50,light:'站在不同專業的交會處。',edge:'線索合理，也可能整條猜錯。',tease:'把推測講得像確認，才是溝通裡真正昂貴的錯。',cost:'你曾從局部 connector 圖面與規格書推測型號，後來 PM 指出方向不對。這個例子提醒的是：能組出合理故事，不等於有足夠證據。技術知識還在補的階段，越想快點交出答案，越需要清楚標示不確定性。',next:'回覆拆成三欄：文件有寫、我推測、待技術確認。還没被證實的內容，就保留為問題，不升格成結論。',ground:'依據：你分享的一次規格判讀經驗；不推論你所有工作都如此。'},
{id:'learning',word:'學習',label:'學習的路徑',cat:'mind',en:'LEARNING',x:76,y:77,light:'把懂了一點，慢慢變成會用。',edge:'跟得上解釋，不等於能自己重做。',tease:'熟悉術語帶來的安心感，可能比實際熟練度來得快。',cost:'你碰過條件判斷、終端機、Commit、Push 和 Pages，但遇到新的操作畫面仍常需要逐步引導。這是正常的入門階段；比較需要小心的是把「我剛剛聽懂了」誤認成「我已經掌握了」。筆記做得漂亮，也不會自動補上操作經驗。',next:'同一件小任務，隔一天不看對話重做一次。記下卡住的步驟，下一次只補那一格，別立刻再開五個新主題。',ground:'依據：你已分享的程式學習與部署操作問題；不等同能力測驗。'},
{id:'aesthetics',word:'審美',label:'審美的直覺',cat:'life',en:'AESTHETICS',x:50,y:88,light:'有秩序，也要有一點性格。',edge:'眼光很挑，規格還可以更清楚。',tease:'「不好看」是有效回饋，但通常還不是可執行的修改指令。',cost:'你能明確感覺模板、字體與色系不對；然而「不夠有趣」「很 AI 感」涵蓋很多問題。這次補上 Sol 的實際參考，就比單獨一個形容詞更能縮小落差。當然，製作者也有責任讀懂參考、主動確認，不能把成品失準全推給你。',next:'每次挑三件事：保留什麼、刪掉什麼、哪個參考的哪個互動值得學。用具體畫面或操作說明取代只增加形容詞。',ground:'依據：這次網站及先前模板修改的對話；責任不是只有需求方。'},
{id:'making',word:'創作',label:'創作的衝動',cat:'mind',en:'MAKING',x:24,y:77,light:'想像出現了，就想讓它能被打開。',edge:'需求跑太快，基礎就會在後面追。',tease:'會叫 AI 做出來，還不等於能掌握它為什麼壞掉。',cost:'你能提出互動、RWD、3D、水流與部署要求，但檔案結構、路徑和發布流程仍在熟悉。當作品規模一下拉大，任何一層出錯都得回頭求援。AI 可以加速產出，也會把尚未理解的複雜度一起打包送來。',next:'先完成一條可分享的小流程：打開首頁、完成一個互動、手機能用。確認後再加下一層；每次記住一個自己能排查的故障。',ground:'依據：你分享過的 3D 網站、檔案與部署困難；不是否定創作方向。'},
{id:'living',word:'生活',label:'生活的節奏',cat:'life',en:'LIVING',x:13,y:50,light:'腦袋之外，也有自己的拍子。',edge:'休息也做成專案，可能更累。',tease:'不是每段空白，都需要變成可以檢核的成果。',cost:'你擅長用清單與工具整理生活，也說過模板太多反而難選。這裡有一個值得留意的可能：如果連休息都要找最佳方法、追蹤成效，工具會開始增加負擔。你說跳舞是為了享受課程，反而是一條很清楚的界線。',next:'保留一段不記錄、不優化的活動。做完只問「有沒有比較舒服」，不用替它產出報告。',ground:'這是從工具使用與休閒偏好提出的提醒，不是已證實的日常模式。'},
{id:'values',word:'價值',label:'關係與世界觀',cat:'life',en:'VALUES',x:24,y:23,light:'保有判斷，也保有溫度。',edge:'看穿問題，不代表已說服別人。',tease:'你的判斷很有理由，對方也未必因此願意配合。',cost:'你曾談到，要讓不同立場的人接受方案很有挑戰。即使判斷成立，溝通仍需要知道對方怕失去什麼、在意什麼、能接受哪一步。若只不斷補強自己的道理，可能會忽略真正卡住的是利益或感受。',next:'在反駁之前，先用一句話重述對方的顧慮，再提出能降低那個顧慮的小方案。這不是認輸，是換一個有效的入口。',ground:'依據：你談過的協調困難；不把偏好獨立判斷等同難相處。'}
];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;
const initial=faces.findIndex(f=>f.id===location.hash.slice(1));let active=initial<0?0:initial,lens='edge';
const originals=faces.map(f=>document.getElementById(f.id).cloneNode(true));
const visited=new Set([active]);const map=document.getElementById('mind-map');const svg=map.querySelector('svg');const nodes=map.querySelector('.map-nodes');const grid=document.getElementById('face-grid');
const positions=faces.map(f=>({x:f.x,y:f.y}));const edges=[[0,3],[0,7],[0,1],[1,2],[1,4],[2,3],[3,5],[4,5],[4,6],[5,6],[6,7]];
const ns='http://www.w3.org/2000/svg';const lines=edges.map(([a,b])=>{const line=document.createElementNS(ns,'line');svg.append(line);return {a,b,line}});
faces.forEach((f,i)=>{const b=document.createElement('button');b.type='button';b.className='map-node';b.dataset.index=i;b.setAttribute('aria-label',f.label+'，點選預覽');b.innerHTML=`<strong>${f.word}</strong><small>${f.en}</small>`;nodes.append(b);const card=document.createElement('button');card.type='button';card.className='face-card';card.dataset.index=i;card.dataset.category=f.cat;card.innerHTML=`<span class="face-head"><span class="eyebrow">0${i+1} / ${f.en}</span><span aria-hidden="true">↗</span></span><span class="face-glyph" aria-hidden="true">${f.word}</span><h3></h3><p></p><span class="face-bottom"><span class="face-mode">直球側寫</span><span class="face-arrow" aria-hidden="true">＋</span></span>`;card.addEventListener('click',()=>openFace(i));grid.append(card)});
const nodeButtons=[...nodes.children];const cards=[...grid.children];const dialog=document.getElementById('face-dialog');let opener=null;
function animate(el,frames=[{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],duration=350){if(!paused&&!reduced.matches&&el.animate)el.animate(frames,{duration,easing:'cubic-bezier(.2,.7,.2,1)'})}
function paintMap(time=0){const shown=positions.map((p,i)=>({x:p.x+(paused||reduced.matches||drag?0:Math.sin(time/2500+i)*.65),y:p.y+(paused||reduced.matches||drag?0:Math.cos(time/2900+i)*.65)}));shown.forEach((p,i)=>{nodeButtons[i].style.setProperty('--x',p.x+'%');nodeButtons[i].style.setProperty('--y',p.y+'%')});lines.forEach(({a,b,line})=>{line.setAttribute('x1',shown[a].x);line.setAttribute('y1',shown[a].y);line.setAttribute('x2',shown[b].x);line.setAttribute('y2',shown[b].y);line.classList.toggle('active',a===active||b===active)})}
function setActive(i){active=(i+faces.length)%faces.length;visited.add(active);const f=faces[active];nodeButtons.forEach((b,j)=>b.setAttribute('aria-pressed',String(j===active)));document.getElementById('peek-label').textContent=`0${active+1} / ${f.label}`;document.getElementById('peek-copy').textContent=f[lens];document.getElementById('visited-count').textContent=`已遇見 ${visited.size} / 8`;animate(document.querySelector('.peek'));paintMap()}
function setLens(value){lens=value;document.querySelectorAll('[data-lens]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lens===lens)));cards.forEach((card,i)=>{card.querySelector('h3').textContent=faces[i][lens];card.querySelector('p').textContent=lens==='edge'?faces[i].tease:originals[i].querySelector('.lead').textContent;card.querySelector('.face-mode').textContent=lens==='edge'?'直球側寫':'亮面側寫';card.setAttribute('aria-label','打開'+faces[i].label+'：'+faces[i][lens])});setActive(active)}
function renderDialog(i){setActive(i);const f=faces[active];const clone=originals[active].cloneNode(true);clone.removeAttribute('id');clone.removeAttribute('aria-labelledby');clone.querySelectorAll('[id]').forEach(e=>e.removeAttribute('id'));clone.querySelector('h3').id='dialog-title';clone.querySelectorAll('.chapter-top,.chapter-footer').forEach(e=>e.remove());clone.querySelectorAll('details').forEach(e=>e.open=false);const note=document.createElement('section');note.className='edge-note';note.innerHTML=`<p class="eyebrow">THE EDGE / 直球觀察</p><h4>${f.edge}</h4><p>${f.cost}</p><p class="next-step"><strong>可以練的下一步</strong><br>${f.next}</p><small>${f.ground}</small>`;const insight=clone.querySelector('.chapter-insight');if(lens==='edge')clone.insertBefore(note,clone.querySelector('.lead'));else insight.after(note);document.getElementById('dialog-content').replaceChildren(clone);document.getElementById('dialog-label').textContent=`0${active+1} / ${f.label}`;document.getElementById('dialog-count').textContent=`${active+1} / 8`;dialog.scrollTop=0;animate(document.getElementById('dialog-content'))}
function openFace(i){if(!dialog.open)opener=document.activeElement;renderDialog(i);if(!dialog.open){dialog.showModal();document.body.classList.add('modal-open');document.getElementById('close-dialog').focus()}history.replaceState(null,'','#'+faces[active].id)}
function closeFace(){dialog.close()}
dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');history.replaceState(null,'','#layers');if(opener&&opener.isConnected)opener.focus({preventScroll:true})});
dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeFace()});
document.getElementById('close-dialog').addEventListener('click',closeFace);document.getElementById('prev-face').addEventListener('click',()=>openFace(active-1<0?7:active-1));document.getElementById('next-face').addEventListener('click',()=>openFace((active+1)%8));document.getElementById('peek-open').addEventListener('click',()=>openFace(active));
document.querySelectorAll('[data-lens]').forEach(b=>b.addEventListener('click',()=>setLens(b.dataset.lens)));
let randomBag=[];document.getElementById('random-face').addEventListener('click',()=>{if(!randomBag.length)randomBag=faces.map((_,i)=>i).filter(i=>i!==active).sort(()=>Math.random()-.5);setActive(randomBag.pop());animate(document.querySelector('.map-core'),[{transform:'translate(-50%,-50%) scale(.9)'},{transform:'translate(-50%,-50%) scale(1)'}],500)});
let drag=null,suppressClick=-1;nodeButtons.forEach((b,i)=>{b.addEventListener('click',e=>{if(suppressClick===i){suppressClick=-1;return}setActive(i)});b.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={i,pointer:e.pointerId,startX:e.clientX,startY:e.clientY,offsetX:positions[i].x,offsetY:positions[i].y,moved:false};b.setPointerCapture(e.pointerId)});b.addEventListener('pointermove',e=>{if(!drag||drag.i!==i||drag.pointer!==e.pointerId)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;if(Math.hypot(dx,dy)>6)drag.moved=true;if(!drag.moved)return;b.classList.add('dragging');const r=map.getBoundingClientRect(),pad=(b.offsetWidth/2+8)/r.width*100;positions[i].x=Math.max(pad,Math.min(100-pad,drag.offsetX+dx/r.width*100));positions[i].y=Math.max(pad,Math.min(100-pad,drag.offsetY+dy/r.height*100));paintMap()});function finish(e){if(!drag||drag.i!==i||drag.pointer!==e.pointerId)return;if(drag.moved)suppressClick=i;drag=null;b.classList.remove('dragging');paintMap();setTimeout(()=>{suppressClick=-1},0)}b.addEventListener('pointerup',finish);b.addEventListener('pointercancel',finish);b.addEventListener('lostpointercapture',finish);b.addEventListener('keydown',e=>{const delta={ArrowLeft:[-2,0],ArrowRight:[2,0],ArrowUp:[0,-2],ArrowDown:[0,2]}[e.key];if(!delta)return;e.preventDefault();const pad=(b.offsetWidth/2+8)/map.clientWidth*100;positions[i].x=Math.max(pad,Math.min(100-pad,positions[i].x+delta[0]));positions[i].y=Math.max(pad,Math.min(100-pad,positions[i].y+delta[1]));paintMap()})});
document.getElementById('reset-map').addEventListener('click',()=>{faces.forEach((f,i)=>Object.assign(positions[i],{x:f.x,y:f.y}));paintMap();animate(map)});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));grid.classList.toggle('filtered',filter!=='all');cards.forEach(c=>{c.hidden=filter!=='all'&&c.dataset.category!==filter;if(!c.hidden)animate(c)})}));
const trails=[{steps:['這句日文自然嗎？','語氣到底差在哪？','對方會理解成哪種立場？','先等一下：這封信要他回什麼？'],comments:['問題很小。暫時。','語感雷達啟動。','已進入商務溝通深水區。','句子終於更精確了。結論也要記得浮上來。']},{steps:['霧面貼為什麼看起來暗？','散射的光跑到哪裡？','眩光、反射、對比差在哪？','先回到手上的實際使用情境。'],comments:['從每天看得到的地方開始。','生活問題，開始接上物理。','三個名詞，每個都能再開一頁。','理解有了。也可以先把手機放下，回去做正事。']},{steps:['我想要一個互動網站。','手機要好用，還要能分享。','檔案、路徑、部署都得接起來。','先做一個自己能修好的小版本。'],comments:['想像力已經上線。','需求正在自然繁殖。','美學在前面跑，終端機在後面追。','能打開是開始；知道壞在哪裡，才多一點主導權。']}];let trail=0,step=0;
function renderTrail(){document.getElementById('trail-count').textContent=String(step+1).padStart(2,'0');const list=document.getElementById('trail-path');list.innerHTML=trails[trail].steps.slice(0,step+1).map((s,i)=>`<li><span>0${i+1}</span>${s}</li>`).join('');document.getElementById('trail-comment').textContent=trails[trail].comments[step];const next=document.getElementById('trail-next');next.textContent=step===3?'這條想完了 ✓':'再往下想一點 ＋';next.disabled=step===3;animate(list.lastElementChild)}
document.querySelectorAll('[data-trail]').forEach(b=>b.addEventListener('click',()=>{trail=Number(b.dataset.trail);step=0;document.querySelectorAll('[data-trail]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderTrail()}));document.getElementById('trail-next').addEventListener('click',()=>{if(step<3)step++;renderTrail()});document.getElementById('trail-reset').addEventListener('click',()=>{step=0;renderTrail()});
const times=[['2024','從理解自己開始。','閱讀大腦科學與學習方法，談心理、書寫、社群使用，也談跳舞。關心知識如何實際改變生活。','看得更深之後，仍要回到「我今天能做什麼」。'],['2025','把語言磨得更細。','持續練習日文表達，推敲商務書信的準確與自然，也更清楚地說出自己的相處偏好與生活期待。','精準的句子，需要搭配同樣清楚的核心訊息。'],['2026','開始做出想像。','走進顯示產業，從 Python 基礎、筆記系統，摸索到互動網頁、GitHub 部署與 3D 空間。問題逐漸從「這是什麼」變成「能不能做出來」。','企圖心已經長大，現在輪到操作基本功慢慢跟上。']];
function renderTime(i){const t=times[i],c=document.getElementById('time-card');c.innerHTML=`<p class="eyebrow">${t[0]} / FIELD NOTES</p><h3>${t[1]}</h3><p>${t[2]}</p><p class="time-edge">留給這一頁的提醒：${t[3]}</p>`;animate(c)}document.querySelectorAll('[data-year]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-year]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderTime(Number(b.dataset.year))}));
let swipe=null;const content=document.getElementById('dialog-content');content.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;swipe={x:e.touches[0].clientX,y:e.touches[0].clientY}}, {passive:true});content.addEventListener('touchend',e=>{if(!swipe)return;const dx=e.changedTouches[0].clientX-swipe.x,dy=e.changedTouches[0].clientY-swipe.y;swipe=null;if(Math.abs(dx)>85&&Math.abs(dx)>Math.abs(dy)*2&&!String(getSelection()))openFace((active+(dx<0?1:7))%8)}, {passive:true});content.addEventListener('touchcancel',()=>swipe=null,{passive:true});
let frame=0,mapVisible=true;function loop(t){frame=0;if(paused||reduced.matches||document.hidden||!mapVisible)return;paintMap(t);frame=requestAnimationFrame(loop)}function startLoop(){if(!frame&&!paused&&!reduced.matches&&!document.hidden&&mapVisible)frame=requestAnimationFrame(loop)}function syncMotion(){document.body.classList.toggle('paused',paused||reduced.matches);const b=document.querySelector('.motion-control');b.setAttribute('aria-pressed',String(paused||reduced.matches));b.textContent=paused||reduced.matches?'動態已暫停':'暫停動態';if(frame){cancelAnimationFrame(frame);frame=0}paintMap();startLoop()}document.querySelector('.motion-control').addEventListener('click',()=>{paused=!paused;syncMotion()});reduced.addEventListener('change',()=>{paused=reduced.matches;syncMotion()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&frame){cancelAnimationFrame(frame);frame=0}else startLoop()});
if('IntersectionObserver'in window){new IntersectionObserver(e=>{mapVisible=e[0].isIntersecting;startLoop()}).observe(map);const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');obs.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.trails,.time-layout,.closing').forEach(el=>{el.classList.add('reveal-ready');obs.observe(el)})}
addEventListener('hashchange',()=>{const i=faces.findIndex(f=>f.id===location.hash.slice(1));if(i>=0)openFace(i)});
setLens('edge');renderTrail();renderTime(0);document.body.classList.add('enhanced');syncMotion();if(initial>=0)openFace(initial);
